syntax = "proto3";

package todoapi;
option go_package = "grpc-go-server/grpcapi";

service TodoService {
  rpc CreateTodo(CreateTodoRequest) returns (CreateTodoResponse);
  rpc GetTodo(GetTodoRequest) returns (GetTodoResponse);
  rpc ListTodos(ListTodosRequest) returns (stream ListTodosResponse);
  rpc UpdateTodo(UpdateTodoRequest) returns (UpdateTodoResponse);
  rpc DeleteTodo(DeleteTodoRequest) returns (DeleteTodoResponse);
}

message Todo {
  string id = 1;
  string title = 2;
  string description = 3;
  bool done = 4;
}

message CreateTodoRequest {
  string title = 1;
  string description = 2;
}
message CreateTodoResponse {
  Todo todo = 1;
}

message GetTodoRequest {
  string id = 1;
}
message GetTodoResponse {
  Todo todo = 1;
}

message ListTodosRequest {}
message ListTodosResponse {
  Todo todo = 1;
}

message UpdateTodoRequest {
  string id = 1;
  string title = 2;
  string description = 3;
  bool done = 4;
}
message UpdateTodoResponse {
  Todo todo = 1;
}

message DeleteTodoRequest {
  string id = 1;
}
message DeleteTodoResponse {
  string id = 1;
}
